version: '3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - sonar-data:/opt/sonarqube/data
    environment:
      - SONAR_FORCEAUTHENTICATION=false

volumes:
  sonar-data: