/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.shyshkin.study.gradle.assignment;

import java.math.BigDecimal;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        var book = new Product("Redmibook 16 Ryzen", "Best book ever", new BigDecimal("1000.00"));

        System.out.println(book);
    }
}
