version: '3'

services:

  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: art
      MYSQL_PASSWORD: 123art123
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 23306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data:
